name: BamBuddy
version: "1.0.22"
slug: bambuddy
description: Self-hosted command center for Bambu Lab printers. No cloud required.
url: https://github.com/naked-head/homeassistant-addons
image: ghcr.io/naked-head/ha-app-bambuddy-{arch}
arch:
  - aarch64
  - amd64
init: false
homeassistant_api: true
host_network: true
map:
  - addon_config:rw
  - data:rw
  - share:rw
  - media:rw
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: BamBuddy Web UI
options:
  log_level: "info"
  trusted_frame_origins: []
  share_subfolders: []
  media_subfolders: []
  use_system_trust_store: false
  enable_ipv6: false
schema:
  bind_address: "str?"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  trusted_frame_origins:
    - "str"
  ha_url: "str?"
  ha_token: "password?"
  database_url: "password?"
  share_subfolders:
    - "str"
  media_subfolders:
    - "str"
  use_system_trust_store: "bool"
  certfile: "str?"
  enable_ipv6: "bool?"
webui: http://[HOST]:[PORT:8000]
